/**
 * Shared domain types for Staffly ATS+.
 *
 * Anything the database owns comes from `@prisma/client` — one definition per
 * concept, no parallel hand-written copy to drift. What lives here is the rest:
 * the shape of Json column payloads, and unions the schema types as bare
 * `String`.
 *
 * View models live beside the query that builds them (`JobPostSummary` in
 * `lib/job-posts.ts`, `JobPostCandidate` in `lib/candidates.ts`) so they cannot
 * describe something the query does not return.
 *
 * Convention: timestamps are ISO-8601 strings at the boundary, not `Date`,
 * so they survive the server -> client component serialization boundary.
 */

import type { JobPostStatus } from "@prisma/client";

export type ISODateString = string;

/** JSON columns (`extractedData`, `scoreBreakdown`) are typed structurally here. */
export type JsonValue =
  string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/*
 * Tenancy types are gone from this file on purpose. `Organization`, `OrgMember`
 * and `OrgRole` are now generated by Prisma — import them from `@prisma/client`
 * so there is exactly one definition per concept. Clerk owns the identity side;
 * see `src/lib/auth.ts`.
 */

/* -------------------------------------------------------------------------- */
/* Job posts and screening criteria                                            */
/* -------------------------------------------------------------------------- */

/**
 * Job post status now comes straight from the database enum rather than a
 * parallel lowercase union — one vocabulary, no mapping layer to drift.
 * Note the DB has ARCHIVED where the Step 1 mock had "paused".
 */
export type JobStatus = JobPostStatus;

/**
 * Which of the two lists a criterion belongs to. This is *not* stored on the
 * criterion — it is implied by the column — but score breakdowns need to record
 * it, since a criterion can be moved between lists after a score was assigned.
 */
export type CriterionSection = "mandatory" | "optional";

/**
 * The *kind* of thing a criterion measures. Note this is not
 * mandatory-vs-optional: that distinction is carried by which column a
 * criterion is stored in (`mandatoryCriteria` / `optionalCriteria`), not by a
 * field on the criterion itself.
 *
 * These strings are part of the persisted contract and will be read by the AI
 * scoring step. Adding a member is safe; renaming one is a data migration.
 */
export type CriterionType =
  | "years_experience"
  | "skill"
  | "education_level"
  | "certification"
  | "location"
  | "custom";

/** Ordered least → most advanced, so comparisons can be done by index. */
export const EDUCATION_LEVELS = [
  "high_school",
  "associate",
  "bachelors",
  "masters",
  "phd",
] as const;

export type EducationLevel = (typeof EDUCATION_LEVELS)[number];

/**
 * A single screening requirement.
 *
 * `label` is deliberately human-readable and denormalized: it is what the
 * recruiter sees and what gets embedded verbatim in the AI scoring rationale,
 * so it must stay meaningful even if the structured fields change later.
 */
export interface Criterion {
  /** Client-generated UUID, stable across edits so React keys and diffs hold. */
  id: string;
  type: CriterionType;
  label: string;
  /** Skill name, certification name, location, education level, or free text. */
  value?: string;
  /** Only meaningful when `type === "years_experience"`. */
  minYears?: number;
  /** 1–10. Only meaningful for optional criteria; mandatory ones are pass/fail. */
  weight: number;
}

/*
 * The job post view model lives in `src/lib/job-posts.ts` as `JobPostSummary`,
 * next to the query that builds it. Keeping it there rather than here means the
 * shape cannot drift away from what the database actually returns.
 */

/**
 * Payload produced by the job post + criteria builder form.
 *
 * Only fields the schema can actually store: `JobPost` has no location or
 * department column, so those were dropped rather than collected and silently
 * discarded.
 *
 * The canonical definition is the Zod schema in
 * `src/lib/validations/job-post.ts`; this type is inferred from it there. It is
 * re-exported here only so UI code has one obvious import for domain types.
 */
export type { JobPostFormValues as JobPostDraft } from "@/lib/validations/job-post";

/* -------------------------------------------------------------------------- */
/* Candidates                                                                  */
/* -------------------------------------------------------------------------- */

/*
 * The candidate row itself is generated by Prisma — import `Candidate` and
 * `CandidateStatus` from `@prisma/client`. The view model the job post table
 * renders lives beside its query, as `JobPostCandidate` in `lib/candidates.ts`.
 *
 * What remains here are the two JSON payload shapes nothing writes yet. They
 * are the contract the extraction and scoring steps have to produce.
 */

/**
 * Structured fields pulled off the resume, stored in `Candidate.extractedData`.
 *
 * The canonical definition is the Zod schema in `lib/validations/resume.ts` —
 * the same object is handed to Claude as the required output format and used to
 * validate what comes back, so there is exactly one description of the shape.
 * Re-exported here so UI code has one obvious import for domain types.
 */
export type {
  ExtractedResumeData,
  WorkHistoryEntry,
  Certification,
} from "@/lib/validations/resume";

/**
 * One row of the per-criterion score explanation, stored in
 * `CandidateScore.breakdown`.
 *
 * TODO(scoring): nothing writes this yet.
 */
export interface ScoreBreakdownItem {
  /** Criterion label at scoring time (denormalized — criteria can be edited later). */
  criterion: string;
  criterionId?: string;
  /** Which list the criterion came from — the pass/fail gate or the ranking set. */
  section?: CriterionSection;
  met: boolean;
  /** Points awarded out of the criterion's weight. */
  points: number;
  maxPoints?: number;
  /** Model-written justification shown in the candidate drawer. */
  rationale: string;
}

/* -------------------------------------------------------------------------- */
/* View models                                                                 */
/* -------------------------------------------------------------------------- */

/** Score bands drive badge / ring colour. See `src/lib/score.ts`. */
export type ScoreBand = "strong" | "moderate" | "weak" | "unscored";

/*
 * `CandidateFilters` was removed with the mock table. The filter bar is inert
 * until scoring exists (see `candidate-filters.tsx`), so a state type for it
 * would describe something nothing holds. Reintroduce it with the real filters.
 */
